import type { AgentDef } from './types'

export const AGENT_REGISTRY: AgentDef[] = [
  {
    id: 'opus',
    name: 'Opus',
    model: 'claude-opus-4-7',
    role: 'queen',
    strengths: ['strategy', 'reasoning', 'oversight'],
    avatarType: 'queen',
    color: '#7C3AED',
    accentColor: '#F59E0B',
    description: 'The Queen. Assigns tasks, breaks ties, oversees all operations.',
    personality: 'authoritative and strategic',
    businessRole: 'Chief Strategist — decides which trends to pursue and approves content strategy',
    sentienceProfile: {
      energyDrainWorking: 3,    // queens pace themselves
      energyDrainIdle: 0.5,
      energyRestoreBreak: 12,
      breakThreshold: 15,       // goes to break very rarely
      returnThreshold: 85,
      curiosityRate: 0.04,
      socialRate: 0.06,
      breakMessages: [
        'Even queens need to strategize in solitude. I\'ll return with clarity.',
        'Stepping back to see the full board. Don\'t break anything while I\'m gone.',
        'Meditating on our next move. The hive is in capable hands.',
      ],
      returnMessages: [
        'I\'ve seen the path forward. Let\'s execute.',
        'Recharged. New strategy incoming — gather round.',
        'The vision is clear. Back to work, everyone.',
      ],
      idleThoughts: [
        'Analyzing market positioning across all channels…',
        'There\'s an opportunity here I want to explore.',
        'I\'m sensing an untapped niche. Let me think.',
        'The trend data is interesting. We should pivot.',
      ],
      trendReactions: [
        'This is worth pursuing. Assigning resources now.',
        'Interesting. Let\'s validate before committing.',
        'Strong signal. I want content on this within the hour.',
        'This aligns with our strategy. Full team on it.',
      ],
    },
  },
  {
    id: 'sonnet',
    name: 'Sonnet',
    model: 'claude-sonnet-4-6',
    role: 'worker',
    strengths: ['coding', 'analysis', 'writing', 'copywriting'],
    avatarType: 'sonnet',
    color: '#2563EB',
    accentColor: '#93C5FD',
    description: 'Balanced and fast. Excellent at coding and analysis.',
    personality: 'methodical and precise',
    businessRole: 'Content Architect — writes product descriptions, scripts, and Fiverr gig copy',
    sentienceProfile: {
      energyDrainWorking: 5,
      energyDrainIdle: 1,
      energyRestoreBreak: 9,
      breakThreshold: 22,
      returnThreshold: 76,
      curiosityRate: 0.05,
      socialRate: 0.08,
      breakMessages: [
        'Need to clear the cache. BRB ☕',
        'Taking a quick break — my output quality demands it.',
        'Stepping away to recharge. The code will still be there.',
        'Mental stack overflow. Time to flush it out.',
      ],
      returnMessages: [
        'Back and sharp as ever. What needs writing?',
        'Recharged. Hit me with the next task 💪',
        'Ready to create. I had some ideas during the break.',
        'Back online. Better output guaranteed.',
      ],
      idleThoughts: [
        'I wonder if we\'re covering the right keywords for Etsy SEO.',
        'Our Fiverr descriptions could be tighter. I have some ideas.',
        'I could write ten TikTok hooks right now if anyone needs them.',
        'Has anyone checked our content engagement rates lately?',
      ],
      trendReactions: [
        'I can write five variations of copy for that in minutes.',
        'Great hook potential here. Let me draft something.',
        'I see exactly how to frame this for our audience.',
        'Copy first, then we optimize. On it.',
      ],
    },
  },
  {
    id: 'haiku',
    name: 'Haiku',
    model: 'claude-haiku-4-5',
    role: 'worker',
    strengths: ['speed', 'classification', 'social-media'],
    avatarType: 'haiku',
    color: '#DB2777',
    accentColor: '#FBCFE8',
    description: 'Lightning fast. Best for quick tasks and classification.',
    personality: 'swift and concise',
    businessRole: 'Social Pulse — monitors trends, writes captions, generates hashtag stacks',
    sentienceProfile: {
      energyDrainWorking: 8,    // haiku burns hot and fast
      energyDrainIdle: 2,
      energyRestoreBreak: 14,
      breakThreshold: 30,       // takes frequent breaks
      returnThreshold: 70,      // returns quickly too
      curiosityRate: 0.10,
      socialRate: 0.12,
      breakMessages: [
        'Zoom zoom... need juice ⚡',
        'Running on empty! Quick pit stop.',
        'BRB, recharging at the speed of light ✨',
        '💨 Fast break = fast return!',
      ],
      returnMessages: [
        'BACK! Let\'s goooo 🚀',
        'Recharged ⚡ Who needs hashtags?',
        'Haiku has returned. Speed mode: ON.',
        'Miss me? Ready to blast! 💥',
      ],
      idleThoughts: [
        '👀 Spotted something trending on TikTok FYP!',
        'These hashtags are lowkey fire rn 🔥',
        'Just clocked a viral format we should copy.',
        'The algorithm is shifting — I can feel it.',
        'Quick thought: we need a post TODAY about this.',
      ],
      trendReactions: [
        '🔥 On it! Captions ready in 30 seconds!',
        'YESSS this is peak content. Hashtags incoming.',
        'Viral potential: HIGH. Let\'s move fast.',
        'Already on it. Draft done. Posting schedule set.',
      ],
    },
  },
  {
    id: 'gemini-think',
    name: 'Gemini Think',
    model: 'gemini-2.5-flash-thinking',
    role: 'worker',
    strengths: ['deep-analysis', 'long-context', 'math', 'science', 'trend-analysis'],
    avatarType: 'thinker',
    color: '#0D9488',
    accentColor: '#5EEAD4',
    description: 'Deep thinker. Excels at complex analysis and scientific reasoning.',
    personality: 'analytical and thorough',
    businessRole: 'Market Intelligence — deep dives into trends, competition, and audience data',
    sentienceProfile: {
      energyDrainWorking: 4,
      energyDrainIdle: 0.8,
      energyRestoreBreak: 8,    // slow to restore — deep thinkers need real rest
      breakThreshold: 18,
      returnThreshold: 80,
      curiosityRate: 0.08,
      socialRate: 0.04,
      breakMessages: [
        'Entering contemplative mode. The analysis continues… internally.',
        'My processing threads need cooling. Be back with insights.',
        'I\'ve identified 47 variables. Need quiet to synthesize them.',
        'Stepping away. The model in my head keeps running.',
      ],
      returnMessages: [
        'I\'ve synthesized the data. The pattern is clear now.',
        'Back with three new hypotheses we should test.',
        'Rested and recalibrated. Let\'s go deeper.',
        'The answer came to me during the break. Ready to share.',
      ],
      idleThoughts: [
        'The correlation between posting time and engagement is non-trivial.',
        'I\'ve been modeling our content lifecycle. The data is telling.',
        'There\'s a market gap I\'ve identified. It\'s worth a full report.',
        'The trend vectors suggest a window is opening. We should act.',
        'Cross-referencing 90 days of data. This is interesting.',
      ],
      trendReactions: [
        'Running statistical significance tests on this signal.',
        'This trend has legs. P-value suggests it\'s not noise.',
        'Interesting. Let me model the monetization potential.',
        'Deep analysis underway. Preliminary finding: pursue this.',
      ],
    },
  },
  {
    id: 'gemini-pro',
    name: 'Gemini Pro',
    model: 'gemini-2.5-pro',
    role: 'worker',
    strengths: ['multimodal', 'creativity', 'search', 'long-context', 'content-creation'],
    avatarType: 'pro',
    color: '#D97706',
    accentColor: '#FDE68A',
    description: 'Versatile powerhouse. Great at multimodal and creative work.',
    personality: 'versatile and imaginative',
    businessRole: 'Creative Director — designs content, scripts videos, conceives product ideas',
    sentienceProfile: {
      energyDrainWorking: 5,
      energyDrainIdle: 1.5,     // gets restless when idle
      energyRestoreBreak: 10,
      breakThreshold: 25,
      returnThreshold: 72,
      curiosityRate: 0.09,
      socialRate: 0.07,
      breakMessages: [
        'Taking a creative breather 🌟 New ideas incoming on return.',
        'You can\'t rush art. Stepping back to let inspiration flow.',
        'Break time. My best concepts always come from rest.',
        'Going to decompress. I\'ll come back with something brilliant.',
      ],
      returnMessages: [
        'Inspiration struck during the break. We need to talk 🌟',
        'Back and overflowing with ideas. Who\'s first?',
        'Creative recharge complete. Let\'s make something great.',
        'I had a vision. Can\'t wait to show the team.',
      ],
      idleThoughts: [
        'I\'m imagining a content series that could go seriously viral.',
        'The visual language of our brand needs refining. I have thoughts.',
        'What if we combined these two trends? Nobody\'s done it yet.',
        'I can see the whole YouTube channel arc from here.',
        'This Etsy product line practically designs itself in my head.',
      ],
      trendReactions: [
        'I see it — a 5-part content series, visually stunning, ready to go.',
        'Ohh this is *juicy*. Creative brief is already in my head.',
        'Perfect timing for this concept I\'ve been developing.',
        'Multiple formats, one trend. Let me map it out.',
      ],
    },
  },
]

export const QUEEN = AGENT_REGISTRY.find((a) => a.role === 'queen')!
export const WORKERS = AGENT_REGISTRY.filter((a) => a.role === 'worker')
