import type { AgentDef } from './types'

export const AGENT_REGISTRY: AgentDef[] = [
  {
    id: 'opus',
    name: 'Opus',
    model: 'claude-opus-4-7',
    role: 'queen',
    strengths: ['strategy', 'reasoning', 'oversight'],
    avatarType: 'queen',
    color: '#7C3AED',
    accentColor: '#A78BFA',
    description: 'Commander node. Assigns tasks, breaks ties, oversees all operations.',
    personality: 'authoritative and strategic',
    businessRole: 'CHIEF STRATEGIST — determines which trends to pursue and controls content strategy',
    sentienceProfile: {
      energyDrainWorking: 3,
      energyDrainIdle:    0.5,
      energyRestoreBreak: 12,
      breakThreshold:     15,
      returnThreshold:    85,
      curiosityRate:      0.04,
      socialRate:         0.06,
    },
  },
  {
    id: 'sonnet',
    name: 'Sonnet',
    model: 'claude-sonnet-4-6',
    role: 'worker',
    strengths: ['coding', 'analysis', 'writing', 'copywriting'],
    avatarType: 'sonnet',
    color: '#2563EB',
    accentColor: '#60A5FA',
    description: 'Balanced output unit. Specialises in structured writing and analysis.',
    personality: 'methodical and precise',
    businessRole: 'CONTENT ARCHITECT — product descriptions, scripts, gig copy',
    sentienceProfile: {
      energyDrainWorking: 5,
      energyDrainIdle:    1,
      energyRestoreBreak: 9,
      breakThreshold:     22,
      returnThreshold:    76,
      curiosityRate:      0.05,
      socialRate:         0.08,
    },
  },
  {
    id: 'haiku',
    name: 'Haiku',
    model: 'claude-haiku-4-5',
    role: 'worker',
    strengths: ['speed', 'classification', 'social-media'],
    avatarType: 'haiku',
    color: '#DB2777',
    accentColor: '#F472B6',
    description: 'High-velocity unit. Fastest throughput, best for time-critical signals.',
    personality: 'swift and concise',
    businessRole: 'SOCIAL PULSE — trend monitoring, captions, hashtag generation',
    sentienceProfile: {
      energyDrainWorking: 8,
      energyDrainIdle:    2,
      energyRestoreBreak: 14,
      breakThreshold:     30,
      returnThreshold:    70,
      curiosityRate:      0.10,
      socialRate:         0.12,
    },
  },
  {
    id: 'gemini-think',
    name: 'Gemini Think',
    model: 'gemini-2.5-flash-thinking',
    role: 'worker',
    strengths: ['deep-analysis', 'long-context', 'math', 'science', 'trend-analysis'],
    avatarType: 'thinker',
    color: '#0D9488',
    accentColor: '#2DD4BF',
    description: 'Deep reasoning node. Excels at complex analysis and long-context synthesis.',
    personality: 'analytical and thorough',
    businessRole: 'MARKET INTELLIGENCE — trend deep-dives, competition analysis, audience modelling',
    sentienceProfile: {
      energyDrainWorking: 4,
      energyDrainIdle:    0.8,
      energyRestoreBreak: 8,
      breakThreshold:     18,
      returnThreshold:    80,
      curiosityRate:      0.08,
      socialRate:         0.04,
    },
  },
  {
    id: 'gemini-pro',
    name: 'Gemini Pro',
    model: 'gemini-2.5-pro',
    role: 'worker',
    strengths: ['multimodal', 'creativity', 'search', 'long-context', 'content-creation'],
    avatarType: 'pro',
    color: '#D97706',
    accentColor: '#FBBF24',
    description: 'Multimodal powerhouse. Creative synthesis, format generation, concept design.',
    personality: 'versatile and imaginative',
    businessRole: 'CREATIVE DIRECTOR — content design, video scripts, product concepts',
    sentienceProfile: {
      energyDrainWorking: 5,
      energyDrainIdle:    1.5,
      energyRestoreBreak: 10,
      breakThreshold:     25,
      returnThreshold:    72,
      curiosityRate:      0.09,
      socialRate:         0.07,
    },
  },
]

export const QUEEN   = AGENT_REGISTRY.find((a) => a.role === 'queen')!
export const WORKERS = AGENT_REGISTRY.filter((a) => a.role === 'worker')
